INSERT INTO excerpts (author, title, description, body) VALUES ('Robert Frost', 'The Road Not Taken', 'Published in 1962 as the first poem in the collection, "Mountain Interval"',  'I shall be telling this with a sigh, somewhere ages and ages hence; two roads diverged in a wood, and I, I took the one less traveled by. And that has made all the difference.');
INSERT INTO excerpts (author, title, description, body) VALUES ('JRR Tolkien', 'The Hobbit', 'The Hobbit, prequel to the famous Lord of the Rings series, was actually published before the LotR trilogy.',  '"What do you mean?" Gandalf said. "Do you wish me a good morning, or mean that it is a good morning whether I want it or not; or that you feel good this morning; or that it is a morning to be good on?"');
INSERT INTO excerpts (author, title, description, body) VALUES ('Death Cab for Cutie', 'I Will Follow You Into the Dark', '"It''s just this idea that what if somebody dies and we''re just floating, just stumbling around in infinite darkness, and I''m just trying to find some kind of spiritual kind of peace with myself, and the world." -Ben Gibbard',  'If heaven and hell decide that they both are satisfied; illuminate the ''No''s on their vacancy signs; if there''s no one beside you, when your soul embarks; then I''ll follow you into the dark.');

INSERT INTO excerpts (author, title, description, body) VALUES ('George Orwell', '1984', '1984, released in 1949, has found it''s place on the best-seller list in four different decades.', 'The Ministry of Truth, which concerned itself with news, entertainment, education and the fine arts. The Ministry of Peace, which concerned itself with war. The Ministry of Love, which maintained law and order. And the Ministry of Plenty, which was responsible for economic affairs. Their names, in Newspeak: Minitrue, Minipax, Miniluv and Miniplenty.');
INSERT INTO excerpts (author, title, description, body) VALUES ('Adrian Salic', 'Cell Biology for Seminars', 'The Mitochondria is the powerhouse of the cell.', 'Mitochondria, the so-called "powerhouses" of cells, are unusual organelles in that they are surrounded by a double membrane and retain their own small genome. They also divide independently of the cell cycle by simple fission. Mitochondrial division is stimulated by energy demand, so cells with an increased need for energy contain greater numbers of these organelles than cells with lower energy needs.');
INSERT INTO excerpts (author, title, description, body) VALUES ('Tom Waits', 'quoted', 'Pulled from a 2011 New York Times interview with Tom.', 'All records are riddles, and whatever you may want people to think it''s about, it may just be throwing them off. And you don''t want it to get in the way of what someone else''s understanding is. It''s not really about anything. At the same time, it will find some meaning.');
INSERT INTO excerpts (author, title, description, body) VALUES ('Dr. Seuss', 'So Late So Soon', 'Several of Seuss'' poems have been misattributed to him, but not this one. Definitely not this one.', 'How did it get so late so soon? It''s night before it''s afternoon. December is here before it''s June. My goodness how the time has flewn. How did it get so late so soon?');
INSERT INTO excerpts (author, title, description, body) VALUES ('F. Scott Fitzgerald', 'The Great Gatsby', 'Now widely acclaimed as one of the best books of all time, when it was first published in April 1925, The Great Gatsby received mixed reviews and sold poorly. In its first year, the book sold only 20,000 copies.', 'I felt a haunting loneliness sometimes, and felt it in others; young clerks in the dusk, wasting the most poignant moments of night and life.');
INSERT INTO excerpts (author, title, description, body) VALUES ('Amelia Earhart', 'quoted', 'In March of 2018, a forensics report was released claiming to identify recovered pacific island remains as Amelia Earhart', 'Among all the marvels of modern invention, that with which I am most concerned, is of course, air transportation. Flying is perhaps the most dramatic of recent scientific attainment. In the brief span of thirty-odd years, the world has seen an inventor''s dream, first materialized by the Wright Brothers at Kitty Hawk, become an everyday actuality. Perhaps I''m prejudiced, but to me it seems that no other phase of modern progress contrives to maintain such a brimming measure of romance and beauty, coupled with utility as does aviation.');
